import type { NextPage } from "next";
import Head from "next/head";
import { useState } from "react";
import Footer from "../components/footer";

const AddChore: NextPage = (props) => {
  const [name, setName] = useState("");
  const [description, setDescription] = useState("");

  const addChore = () => {
    console.log(name, description);
    return false;
  };

  return (
    <>
      <Head>
        <title>Add Chore</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="container mx-auto flex min-h-screen flex-col items-center justify-center p-4">
        <div className="flex w-full items-center justify-center pt-6 text-2xl text-blue-500">
          Add Chore
        </div>
        <form name="addChore">
          Name:{" "}
          <input
            type="text"
            name="name"
            className="border"
            value={name}
            onChange={(e) => setName(e.target.value)}
          />
          <br />
          Description:{" "}
          <input
            type="text"
            name="description"
            className="border"
            value={description}
            onChange={(e) => setDescription(e.target.value)}
          />
          <br />
          <button
            onClick={addChore}
            className="rounded border border-blue-700 bg-blue-500 py-2 px-4 font-bold text-white hover:bg-blue-700"
          >
            Submit
          </button>
        </form>

        <Footer />
      </main>
    </>
  );
};

export default AddChore;
