import type { NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import Footer from "../components/footer";
import { trpc } from "../utils/trpc";

const Home: NextPage = (props) => {
  const chores = trpc.chores.getAll.useQuery();

  return (
    <>
      <Head>
        <title>Chore Helper</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="container mx-auto flex min-h-screen flex-col items-center justify-center p-4">
        <div className="flex w-full items-center justify-center pt-6 text-2xl text-blue-500">
          {chores.data?.map((chore) => {
            return <div key={chore.id}>{chore.description}</div>;
          })}
        </div>

        <Footer />
      </main>
    </>
  );
};

export default Home;
